### ISSUE TITLE
suddenly plejd stopped working

### ISSUE THREAD

**Issue by kraexx** [klali/ha-plejd#59]
Hi!
First of, thanks for a wonderfull function for HA!
have been running this for quite some time, with no problems what so ever, but now suddenly it has stopped working. What can be the problem??

Config: {
  site: 'Hillaredplejd',
  username: '---scrubbed---',
  password: '---scrubbed---',
  mqttBroker: 'mqtt://192.168.1.226/',
  mqttUsername: 'krexx',
  mqttPassword: '---scrubbed---',
  includeRoomsAsLights: true,
  preferCachedApiResponse: false,
  updatePlejdClock: false,
  logLevel: 'info',
  connectionTimeout: 20,
  writeQueueWaitTime: 1300
}
2022-11-13 00:59:51 INF [plejd-main] Log level set to info
Starting Plejd addon and reading configuration...
2022-11-13 00:59:51 INF [plejd-main] Log level set to info
2022-11-13 00:59:51 INF [plejd-main] Plejd add-on, version 0.9.1
2022-11-13 00:59:51 INF [device-comm] Starting Plejd communication handler.
2022-11-13 00:59:51 INF [plejd-ble] Starting Plejd BLE Handler, resetting all device states.
2022-11-13 00:59:51 INF [plejd-main] Main Plejd addon init()...
2022-11-13 00:59:51 INF [plejd-api] init()
2022-11-13 00:59:51 INF [plejd-api] Getting cached api response from disk
2022-11-13 00:59:51 INF [plejd-api] login()
2022-11-13 00:59:51 INF [plejd-api] logging into Hillaredplejd
2022-11-13 00:59:52 INF [plejd-api] got session token response
2022-11-13 00:59:52 INF [plejd-api] Get all Plejd sites for account...
2022-11-13 00:59:52 INF [plejd-api] Got site list response with 1: Hillaredplejd
2022-11-13 00:59:52 INF [plejd-api] Site found matching configuration name Hillaredplejd
2022-11-13 00:59:52 INF [plejd-api] Get site details for 27fe46a9-68da-4869-9e89-8635cc84f773...
2022-11-13 00:59:53 INF [plejd-api] got site details response
2022-11-13 00:59:53 INF [plejd-api] Site details for site id 27fe46a9-68da-4869-9e89-8635cc84f773 found
2022-11-13 00:59:53 INF [plejd-api] Saving cached copy
2022-11-13 00:59:53 INF [plejd-api] Getting devices from site details response...
2022-11-13 00:59:53 INF [plejd-api] No Plejd gateway found on site
2022-11-13 00:59:53 INF [plejd-mqtt] Initializing MQTT connection for Plejd addon
2022-11-13 00:59:53 INF [plejd-ble] init()
2022-11-13 00:59:54 INF [plejd-mqtt] Connected to MQTT.
2022-11-13 00:59:54 INF [plejd-mqtt] Sending discovery for 4 Plejd output devices
2022-11-13 00:59:54 INF [plejd-mqtt] Discovered DIM-01 (light) named Belysning vägg  (11 : D8750833883C_0).
2022-11-13 00:59:54 INF [plejd-mqtt] Discovered DIM-01 (light) named Takbelysning köksbord (12 : FE18E394FF8A_0).
2022-11-13 00:59:54 INF [plejd-mqtt] Discovered DIM-01 (light) named Belysning fönster (13 : E20EF99234E1_0).
2022-11-13 00:59:54 INF [plejd-mqtt] Discovered Room (light) named Kök / Matplats (10 : ea29b72c-b304-4fde-89c5-15fdfdf09830).
2022-11-13 00:59:54 INF [plejd-mqtt] Sending discovery for 0 Plejd input devices
2022-11-13 00:59:54 INF [plejd-mqtt] Sending discovery for 0 Plejd scene devices
2022-11-13 00:59:54 INF [device-comm] Plejd got turn off command for Belysning vägg  (D8750833883C_0)
2022-11-13 00:59:54 INF [device-comm] Plejd got turn on command for Takbelysning köksbord (FE18E394FF8A_0), brightness undefined
2022-11-13 00:59:54 INF [device-comm] Plejd got turn off command for Belysning fönster (E20EF99234E1_0)
2022-11-13 00:59:54 INF [device-comm] Plejd got turn off command for Kök / Matplats (ea29b72c-b304-4fde-89c5-15fdfdf09830)
2022-11-13 00:59:59 INF [plejd-ble] BLE init done, waiting for devices.
2022-11-13 00:59:59 INF [plejd-main] Main init done
2022-11-13 00:59:59 INF [plejd-main] main() finished
2022-11-13 01:00:19 ERR [plejd-ble] Discovery timeout elapsed, no devices found. Starting reconnect loop...
2022-11-13 01:00:19 INF [plejd-ble] Starting reconnect loop...
2022-11-13 01:00:19 INF [device-comm] Bluetooth reconnecting...
2022-11-13 01:00:24 INF [plejd-ble] Reconnecting BLE...
2022-11-13 01:00:24 INF [plejd-ble] init()
2022-11-13 01:00:29 ERR [plejd-ble] Failed to start discovery. Operation already in progress
DBusError: Operation already in progress
    at _methodReturnHandlers.<computed> (/plejd/node_modules/dbus-next/lib/bus.js:343:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:101:11)
    at EventEmitter.<anonymous> (/plejd/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (events.js:314:20)
    at /plejd/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
2022-11-13 01:00:29 INF [plejd-ble] If you continue to get "operation already in progress" error, you can try power cycling the bluetooth adapter. Get root console access, run "bluetoothctl" => "power off" => "power on" => "exit" => restart addon.
2022-11-13 01:00:29 WRN [plejd-ble] Failed reconnecting. Failed to start discovery. Make sure no other add-on is currently scanning.
Error: Failed to start discovery. Make sure no other add-on is currently scanning.
    at PlejBLEHandler._startGetPlejdDevice (/plejd/PlejdBLEHandler.js:436:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-11-13 01:00:29 INF [device-comm] Bluetooth reconnecting...

**Comment by kraexx** [comment]
and now it just works again..... this is strange...

**Comment by klali** [comment]
it looks like you're using https://github.com/icanos/hassio-plejd and not this integration, so you'll have to ask there.
